[build]
builder = "nixpacks"
buildCommand = "echo 'Сборка Split Online Game...'"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100

# Настройки для WebSocket приложения
[variables]
NODE_ENV = "production" 